### PR TITLE
Rebuild for libboost 1.82 + flann 1.9.2 + CUDA 11.8 + CUDA 12

### PR DESCRIPTION
**Pull request by h-vetinari**
Bot could not open a PR due to pybind pin

### CODE REVIEW

**Comment by h-vetinari** [comment]
@Tobias-Fischer 
So I unpinned pybind here, because that's what kept the bot from opening this PR, but it seems this might be the reason this is now failing:
```
import: 'pycolmap'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pycolmap_1696851618019/test_tmp/run_test.py", line 2, in <module>
    import pycolmap
ImportError: generic_type: cannot initialize type "KeysView[int]": an object with that name is already defined
```
Any ideas?

**Comment by h-vetinari** [comment]
Gentle ping @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
I think we might be running into https://github.com/pybind/pybind11/issues/4529

**Comment by Tobias-Fischer** [comment]
The pybind11 issue seems to be resolved.

We are now running into the same issues as in #9:
```
  /home/conda/feedstock_root/build_artifacts/pycolmap_1697589028940/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/10.4.0/../../../../aarch64-conda-linux-gnu/bin/ld: /usr/local/cuda/lib64/libcudart_static.a(cudart_static.o): Relocations in generic ELF (EM: 62)
```

I have no idea how to tackle it though, and I am not sure why it appears now.

**Comment by jakirkham** [comment]
Well it is linking to the `x86_64` library while building of `aarch64`. The linker understandably errors

The question is, what is handing the linker the `x86_64` library instead of the `aarch64` library?

This probably involves more knowledge of how the build here occurs (probably combined with more verbose builds)

**Comment by jakirkham** [comment]
Also this warning [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=806263&view=logs&jobId=b7a895b1-8909-5023-4a22-40a4698fe576&j=b7a895b1-8909-5023-4a22-40a4698fe576&t=821caef9-b8fa-5ab7-47a2-7e7cdae7737e ) seems important. Maybe worth raising upstream?

```
  CMake Warning (dev) at /home/conda/feedstock_root/build_artifacts/pycolmap_1697589028940/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/colmap/COLMAPConfig.cmake:211 (find_package):
    Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
    --help-policy CMP0146" for policy details.  Use the cmake_policy command to
    set the policy and suppress this warning.
```

**Comment by Tobias-Fischer** [comment]
I think the issue is that this change has not been incorporated in the CmakeConfig of colmap that is being used here: https://github.com/colmap/colmap/blob/43de802cfb3ed2bd155150e7e5e3e8c8dd5aaa3e/cmake/CMakeConfig.cmake.in#L206

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin  please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Thank you both! 🙏

**Pull request merged**
