### PR TITLE
Feat migrate to main repo

### PR DESCRIPTION
**Pull request by HernandoR**
migrate source from colmap/pycolmap to colmap/colmap

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

relating to #38

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin  please rerender

**Comment by HernandoR** [comment]
cool! may i ask why use tar.gz instead of git ref ? also, which referance can i refering to for the url of the archive?

**Comment by Tobias-Fischer** [comment]
It’s general conda-forge preference to use the .tar.gz - it’s “more archival” than the git ref and helps with reproducible builds.

I’m not sure what you mean with your second question?

**Comment by HernandoR** [comment]
Well, I was asking how could i know the url to download the `.tar.gz`, is there any document? I was manually copy paste from my browser's download page, hope to have a more official source.

**Comment by Tobias-Fischer** [comment]
I see - yes, here: https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml

**Pull request merged**
